# Библиотеки

In [2]:
from sklearn import datasets # для boston
from sklearn import preprocessing # Для масштабирования признаков
from sklearn.neighbors import KNeighborsRegressor # kNN
from sklearn.neighbors import KNeighborsClassifier # kNN
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

# Загружаем выборку Boston
## B['data'] - признаки, B['target'] - ответы(цены)

In [3]:
B = datasets.load_boston()

In [4]:
print(B['data'])
print(B['target'])

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.

# Масштабируем признаки

In [5]:
X = preprocessing.scale(B['data'])

In [6]:
y = B['target']

In [7]:
P = np.linspace(1, 2, num=200)

In [8]:
X

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

## Добавим кросс-валидацию

In [9]:
kf = KFold(shuffle=True,random_state=42)

# Обучение

In [23]:
a = []
for i in P:
    neigh = KNeighborsRegressor(n_neighbors=5, weights='distance', p = i, metric='minkowski')
    neigh.fit(X, y)
    a.append([i,np.mean(cross_val_score(neigh, X, y, scoring='neg_mean_squared_error'))])

In [24]:
a

[[1.0, -27.76759335308547],
 [1.0050251256281406, -27.8275239419346],
 [1.0100502512562815, -27.7689712713689],
 [1.015075376884422, -27.758296013265124],
 [1.020100502512563, -27.62000136016839],
 [1.0251256281407035, -27.65491421159218],
 [1.0301507537688441, -27.646688431579925],
 [1.035175879396985, -27.62035969253523],
 [1.0402010050251256, -27.631865910960727],
 [1.0452261306532664, -27.595617418001495],
 [1.050251256281407, -27.603121630227406],
 [1.0552763819095476, -27.650434400142228],
 [1.0603015075376885, -27.6465487073177],
 [1.065326633165829, -27.574099499318333],
 [1.07035175879397, -27.631000807722103],
 [1.0753768844221105, -27.681108696809947],
 [1.0804020100502512, -27.83639529222022],
 [1.085427135678392, -27.825847603675516],
 [1.0904522613065326, -27.816755471415796],
 [1.0954773869346734, -27.804143285857343],
 [1.100502512562814, -27.801447637230076],
 [1.1055276381909547, -27.671168670630415],
 [1.1105527638190955, -27.5763375685219],
 [1.1155778894472361, -27

In [21]:
max(a)

-26.87405938164519