In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
import re

# Открываем файл

In [2]:
data = pd.read_csv('titanic.csv', index_col = 'PassengerId')
# Сразу удалим ненужные столбцы
data.drop('Ticket', axis = 1, inplace = True)
data.drop('Name', axis = 1, inplace = True)
data.drop('SibSp', axis = 1, inplace = True)
data.drop('Parch', axis = 1, inplace = True)
data.drop('Embarked', axis = 1, inplace = True)
data.drop('Cabin', axis = 1, inplace = True)
data

Survived  Pclass     Sex   Age     Fare
PassengerId                                         
1                   0       3    male  22.0   7.2500
2                   1       1  female  38.0  71.2833
3                   1       3  female  26.0   7.9250
4                   1       1  female  35.0  53.1000
5                   0       3    male  35.0   8.0500
...               ...     ...     ...   ...      ...
887                 0       2    male  27.0  13.0000
888                 1       1  female  19.0  30.0000
889                 0       3  female   NaN  23.4500
890                 1       1    male  26.0  30.0000
891                 0       3    male  32.0   7.7500

[891 rows x 5 columns]

# Матрица признаков

In [3]:
prizn = np.array([data['Pclass'],
                  data['Fare'],
                  data['Sex'].replace("female", 1).replace("male", 0), #Female - 1, male - 0
                  data['Age'],
                  data['Survived']
                 ])
# Транспонируем, для нужного формата
prizn = prizn.transpose()
prizn

array([[ 3.    ,  7.25  ,  0.    , 22.    ,  0.    ],
       [ 1.    , 71.2833,  1.    , 38.    ,  1.    ],
       [ 3.    ,  7.925 ,  1.    , 26.    ,  1.    ],
       ...,
       [ 3.    , 23.45  ,  1.    ,     nan,  0.    ],
       [ 1.    , 30.    ,  0.    , 26.    ,  1.    ],
       [ 3.    ,  7.75  ,  0.    , 32.    ,  0.    ]])

## Удалим из выборки объекты с age = nan

In [4]:
new_prizn = []
for i in range(0,len(prizn)):
    if np.isnan(prizn[i][3]) == False:
        new_prizn.append(prizn[i])
new_prizn = np.array(new_prizn)
new_prizn

array([[ 3.    ,  7.25  ,  0.    , 22.    ,  0.    ],
       [ 1.    , 71.2833,  1.    , 38.    ,  1.    ],
       [ 3.    ,  7.925 ,  1.    , 26.    ,  1.    ],
       ...,
       [ 1.    , 30.    ,  1.    , 19.    ,  1.    ],
       [ 1.    , 30.    ,  0.    , 26.    ,  1.    ],
       [ 3.    ,  7.75  ,  0.    , 32.    ,  0.    ]])

In [5]:
# Транспонируем, для нужного формата
new_prizn = new_prizn.transpose()

In [6]:
#Разделим объекты и их ответы
surv = new_prizn[4]
prizn = new_prizn[:4]

In [7]:
surv = surv.transpose()

In [8]:
prizn = prizn.transpose()

# Решающее дерево

In [9]:
clf = DecisionTreeClassifier()
model = clf.fit(prizn, surv) # Тренировка модели

In [10]:
importances = clf.feature_importances_

In [11]:
importances

array([0.14451298, 0.30242208, 0.30051221, 0.25255273])

## Сделаем предсказание для 22 летней девушки в первом класе с ценой билета 70

In [16]:
x = np.array([ 1.    ,  70.  ,  1.    , 22.  ])

In [19]:
y_pred = model.predict(x.reshape(1, -1))
y_pred

array([1.])